version = 1

exclude_patterns = [
    "frontend/src/components/ui/**",
    "frontend/img",
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser"
  ]