name: Deploy Login API to Lambda

on:
  push:
    branches:
        - main
    paths:
        - 'backend/loginapi/**'    

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: backend/loginapi

      - name: Bundle and zip Lambda
        run: |
          mkdir -p dist
          zip -r dist/lambda.zip . -x "*.git*" "node_modules/aws-sdk/*"
        working-directory: backend/loginapi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_LOGINAPI_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_LOGINAPI_SECRET_ACCESS_KEY }}
            aws-region: us-west-1

      - name: Deploy Lambda code
        run: |
          aws lambda update-function-code \
            --function-name atlaxiom-login-api \
            --zip-file fileb://dist/lambda.zip