name: CI/CD deploy to vps server

on:
  schedule:
    - cron: '59 11 * * *'
  push:
    branches:
      - main

permissions:
  packages: write

jobs:  
  build-and-push-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # v3.0.0

      - name: Log into registry $https://ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/vchen7629/atlaxiom-frontend:prod
          cache-from: type=registry,ref=ghcr.io/vchen7629/frontend-npm-cache:latest

  build-and-push-backend-image:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # v3.0.0

      - name: Log into registry https://ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0 !!
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./loginapi
          file: ./loginapi/Dockerfile
          push: true
          tags: ghcr.io/vchen7629/atlaxiom-backend:prod
          cache-from: type=registry,ref=ghcr.io/vchen7629/loginapi-npm-cache:latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-frontend-image
      - build-and-push-backend-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean Docker resources
        uses: appleboy/ssh-action@v1.2.0
        with: 
          port: 22
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: vchen7629
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            docker image prune --force

      - name: 'Pulling latest container'
        uses: appleboy/ssh-action@v1.2.0
        with: 
          port: 22
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: vchen7629
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd Atlaxiom/
            docker compose pull