name: Build and Push Login API Cache

on:
    schedule:
      - cron: '59 11 * * *'
    push:
        branches:
            - main
        paths:
            - 'emailapi/package.json'
            - 'emailapi/package-lock.json'
            - 'emailapi/Dockerfile'

jobs:
  build-and-push-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push cache
        uses: docker/build-push-action@v5
        with:
          context: ./emailapi
          file: ./emailapi/Dockerfile
          target: cache
          push: true
          tags: ghcr.io/vchen7629/emailapi-npm-cache:latest
          cache-to: type=registry,ref=ghcr.io/vchen7629/emailapi-npm-cache:latest,mode=max