name: Caching Frontend dependencies 

on:
  schedule:
    - cron: '59 11 * * *'
  push:
    branches:
      - main
    #paths:
      #- 'frontend/package.json'
      #- 'frontend/package-lock.json'

jobs: 
    build-and-push-cache:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3 # v3.0.0

            - name: Log into registry https://ghcr.io
              if: github.event_name != 'pull_request'
              uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
              with:
                registry: https://ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Docker Image (Frontend)
              uses: docker/build-push-action@v5
              with:
                context: ./frontend
                file: ./frontend/Dockerfile.frontendcache
                push: ${{ github.event_name != 'pull_request' }}
                tags: ghcr.io/vchen7629/atlaxiom-frontend:prod
                cache-from: type=registry,ref=ghcr.io/vchen7629/atlaxiom-frontend:prod
                cache-to: type=registry,ref=ghcr.io/vchen7629/atlaxiom-frontend:prod,mode=max
        